### PR TITLE
removed the lower limit of pool size

### PR DESCRIPTION
**Pull request by TechAlchemistry**

### CODE REVIEW

**Comment by TechAlchemistry** [comment]
Hi! Why do not you merge this PR?

**Comment by TechAlchemistry** [comment]
... ?

**Comment by qxsch** [comment]
Sorry for my late response, but a workerpool schould have at least one worker. So removing the whole if, introduces a potential bug.
We could consider, changing the value from 2 to 1.

**Comment by TechAlchemistry** [comment]
@qxsch But the `setWorkerPoolSize` method already has a lower limit check.
```
       public function setWorkerPoolSize($size) {
		if ($this->created) {
			throw new WorkerPoolException('Cannot set the Worker Pool Size for a created pool.');
		}
		$size = (int)$size;
		if ($size <= 0) {
			throw new \InvalidArgumentException('"' . $size . '" is not an integer greater than 0.');
		}
		$this->workerPoolSize = $size;
		return $this;
	}
```

**Comment by TechAlchemistry** [comment]
Thank you!

**Comment by qxsch** [comment]
You're welcome! Sorry again for my late response and thank you for your contribution.

**Comment by TechAlchemistry** [comment]
You are welcome ;)

16 сен 2017 г. 15:38 пользователь "qxsch" <notifications@github.com>
написал:

**Pull request merged**
